// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetServerDemo;

#nullable disable

namespace NetServerDemo.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20221004085758_UserImgTableAdd_5")]
    partial class UserImgTableAdd_5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NetServerDemo.DB.Chat", b =>
                {
                    b.Property<int?>("chatID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("chatID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Content");

                    b.Property<DateTime>("CreateTime")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<int?>("RoomNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("RoomNo");

                    b.Property<string>("UserNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserNo");

                    b.HasKey("chatID");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("NetServerDemo.DB.Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<DateTime>("CreateTime")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RoomName");

                    b.HasKey("RoomID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("NetServerDemo.DB.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserID");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserName");

                    b.Property<string>("UserPW")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserPW");

                    b.Property<string>("UserPhon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserPhon");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NetServerDemo.DB.User_Chat", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserID");

                    b.Property<int>("RoomID")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<int?>("ChatID")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("ChatID");

                    b.Property<bool>("Check")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("tinyint(20)")
                        .HasColumnName("Check");

                    b.Property<DateTime>("CreateTime")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.HasKey("UserID", "RoomID", "ChatID");

                    b.ToTable("User_Chats");
                });

            modelBuilder.Entity("NetServerDemo.DB.User_Profile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserID");

                    b.Property<string>("Img")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("longtext")
                        .HasColumnName("Img");

                    b.HasKey("UserId");

                    b.ToTable("User_Profiles");
                });

            modelBuilder.Entity("NetServerDemo.DB.User_Room", b =>
                {
                    b.Property<string>("UserID")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("UserID");

                    b.Property<int>("RoomID")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<DateTime>("CreateTime")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreateTime");

                    b.Property<bool>("RoomLeader")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("RoomLeader");

                    b.HasKey("UserID", "RoomID");

                    b.ToTable("User_Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
