// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PublicDBLib.Migrations
{
    [DbContext(typeof(MariaContext))]
    [Migration("20220810030003_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PublicDBLib.MariaDB.ASOSCodeDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("WPCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("WPCode");

                    b.Property<string>("WPMgrName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("WPMgrName");

                    b.Property<string>("WPName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("WPName");

                    b.Property<decimal>("latitude")
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("Latitude")
                        .HasComment("위도");

                    b.Property<decimal>("longitude")
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("Longitude")
                        .HasComment("경도");

                    b.HasKey("Id");

                    b.HasIndex("WPCode")
                        .IsUnique();

                    b.ToTable("ASOSCodeList");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.ASOSDailyDatum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal?>("avgCm10Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm10Te")
                        .HasComment("평균 10cm 지중온도(c)");

                    b.Property<decimal?>("avgCm20Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm20Te")
                        .HasComment("평균 20cm 지중온도(c)");

                    b.Property<decimal?>("avgCm30Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm30Te")
                        .HasComment("평균 30cm 지중온도(c)");

                    b.Property<decimal?>("avgCm5Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm5Te")
                        .HasComment("평균 5cm 지중온도(c)");

                    b.Property<decimal?>("avgLmac")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgLmac")
                        .HasComment("평균 중하층운량(10분위)");

                    b.Property<decimal?>("avgM05Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM05Te")
                        .HasComment("평균 0.5m 지중온도(c)");

                    b.Property<decimal?>("avgM10Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM10Te")
                        .HasComment("평균 1.0m 지중온도(c)");

                    b.Property<decimal?>("avgM15Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM15Te")
                        .HasComment("평균 1.5m 지중온도(c)");

                    b.Property<decimal?>("avgM30Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM30Te")
                        .HasComment("평균 3.0m 지중온도(c)");

                    b.Property<decimal?>("avgM50Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM50Te")
                        .HasComment("평균 5.0m 지중온도(c)");

                    b.Property<decimal?>("avgPa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgPa")
                        .HasComment("평균 현지기압(hPa)");

                    b.Property<decimal?>("avgPs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgPs")
                        .HasComment("평균 해면기압(hPa)");

                    b.Property<decimal?>("avgPv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgPv")
                        .HasComment("평균 증기압(hPa)");

                    b.Property<decimal?>("avgRhm")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgRhm")
                        .HasComment("평균 상대습도(%)");

                    b.Property<decimal?>("avgTa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTa")
                        .HasComment("평균 기온(c)");

                    b.Property<decimal?>("avgTca")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTca")
                        .HasComment("평균 전운량(10분위)");

                    b.Property<decimal?>("avgTd")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTd")
                        .HasComment("평균 이슬점 온도(c)");

                    b.Property<decimal?>("avgTs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTs")
                        .HasComment("평균 지면온도(c)");

                    b.Property<decimal?>("avgWs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgWs")
                        .HasComment("평균 풍속(m/s)");

                    b.Property<decimal?>("ddMefs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ddMefs")
                        .HasComment("일 최심신적설(cm)");

                    b.Property<string>("ddMefsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ddMefsHrmt")
                        .HasComment("일 최심신적설 시각");

                    b.Property<decimal?>("ddMes")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ddMes")
                        .HasComment("일 최심적설(cm)");

                    b.Property<string>("ddMesHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ddMesHrmt")
                        .HasComment("일 최심적설 시각");

                    b.Property<string>("dt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("dt")
                        .HasComment("변환시간");

                    b.Property<decimal?>("hr1MaxIcsr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hr1MaxIcsr")
                        .HasComment("1시간 최다 일사량(MJ/m2)");

                    b.Property<string>("hr1MaxIcsrHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("hr1MaxIcsrHrmt")
                        .HasComment("1시간 최다 일사시각(hhmi)");

                    b.Property<decimal?>("hr1MaxRn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hr1MaxRn")
                        .HasComment("1시간 최다강수량(mm)");

                    b.Property<string>("hr1MaxRnHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("hr1MaxRnHrmt")
                        .HasComment("1시간 최다강수량 시각");

                    b.Property<short?>("hr24SumRws")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("hr24SumRws")
                        .HasComment("풍정합(100m)");

                    b.Property<string>("iscs")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("iscs")
                        .HasComment("일기현상");

                    b.Property<decimal?>("maxInsWs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxInsWs")
                        .HasComment("최대 순간풍속(m/s)");

                    b.Property<string>("maxInsWsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxInsWsHrmt")
                        .HasComment("최대 순간풍속 시각");

                    b.Property<short?>("maxInsWsWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("maxInsWsWd")
                        .HasComment("최대 순간풍속 풍향(16방위)");

                    b.Property<decimal?>("maxPs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxPs")
                        .HasComment("최고 해면 기압(hPa)");

                    b.Property<string>("maxPsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxPsHrmt")
                        .HasComment("최고 해면기압 시각");

                    b.Property<decimal?>("maxTa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxTa")
                        .HasComment("최고 기온(c)");

                    b.Property<string>("maxTaHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxTaHrmt")
                        .HasComment("최고기온시각");

                    b.Property<short?>("maxWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("maxWd")
                        .HasComment("최다 풍향(16방위)");

                    b.Property<decimal?>("maxWs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxWs")
                        .HasComment("최대 풍속(m/s)");

                    b.Property<string>("maxWsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxWsHrmt")
                        .HasComment("최대 풍속 시각");

                    b.Property<short?>("maxWsWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("maxWsWd")
                        .HasComment("최대 풍속 풍향(16방위)");

                    b.Property<decimal?>("mi10MaxRn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("mi10MaxRn")
                        .HasComment("10분 최다강수량(mm)");

                    b.Property<string>("mi10MaxRnHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("mi10MaxRnHrmt")
                        .HasComment("10분 최다강수량 시각(mm)");

                    b.Property<decimal?>("minPs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minPs")
                        .HasComment("최저 해면기압(hPa)");

                    b.Property<string>("minPsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("minPsHrmt")
                        .HasComment("최저 해면기압 시각");

                    b.Property<decimal?>("minRhm")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minRhm")
                        .HasComment("최소 상대습도(%)");

                    b.Property<string>("minRhmHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("minRhmHrmt")
                        .HasComment("평균 상대습도 시각");

                    b.Property<decimal?>("minTa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minTa")
                        .HasComment("최저 기온(c)");

                    b.Property<string>("minTaHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("minTaHrmt")
                        .HasComment("최저기온시각");

                    b.Property<decimal?>("minTg")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minTg")
                        .HasComment("최저 초상온도(c)");

                    b.Property<decimal?>("n99Rn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("n99Rn")
                        .HasComment("9-9 강수(mm)");

                    b.Property<decimal?>("ssDur")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ssDur")
                        .HasComment("가조시간(hr)");

                    b.Property<string>("stnId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnId")
                        .HasComment("종관기상관측 지점번호");

                    b.Property<string>("stnNm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnNm")
                        .HasComment("종관기상관측 지점명");

                    b.Property<decimal?>("sumDpthFhsc")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumDpthFhsc")
                        .HasComment("합계 3시간 신적설(cm)");

                    b.Property<decimal?>("sumFogDur")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumFogDur")
                        .HasComment("안개 계속 시간(hr)");

                    b.Property<decimal?>("sumGsr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumGsr")
                        .HasComment("합계 일사량(MJ/m2)");

                    b.Property<decimal?>("sumLrgEv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumLrgEv")
                        .HasComment("합계 대형증발량(mm)");

                    b.Property<decimal?>("sumRn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumRn")
                        .HasComment("일강수량(mm)");

                    b.Property<decimal?>("sumRnDur")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumRnDur")
                        .HasComment("강수 계속시간(hr)");

                    b.Property<decimal?>("sumSmlEv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumSmlEv")
                        .HasComment("합계 소형증발량(mm)");

                    b.Property<decimal?>("sumSsHr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumSsHr")
                        .HasComment("합계 일조 시간(hr)");

                    b.Property<DateTime>("tm")
                        .HasColumnType("DATETIME")
                        .HasColumnName("tm")
                        .HasComment("샘플링 시간");

                    b.HasKey("Id");

                    b.HasIndex("stnId", "tm")
                        .IsUnique();

                    b.ToTable("ASOSDailyData");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.ASOSHourDatum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<short?>("clfmAbbrCd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("clfmAbbrCd")
                        .HasComment("운형");

                    b.Property<decimal?>("dc10LmcsCa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("dc10LmcsCa")
                        .HasComment("중하층운량");

                    b.Property<decimal?>("dc10Tca")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("dc10Tca")
                        .HasComment("전운량");

                    b.Property<short?>("dmstMtphNo")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("dmstMtphNo")
                        .HasComment("현상번호");

                    b.Property<decimal?>("dsnw")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("dsnw")
                        .HasComment("적설(cm)");

                    b.Property<short?>("gndSttCd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("gndSttCd")
                        .HasComment("지면상태");

                    b.Property<decimal?>("hm")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hm")
                        .HasComment("습도");

                    b.Property<sbyte>("hmQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("hmQcflag")
                        .HasComment("습도 정상여부 판별 정보");

                    b.Property<decimal?>("hr3Fhsc")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hr3Fhsc")
                        .HasComment("3시간 신적설(cm)");

                    b.Property<decimal?>("icsr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("icsr")
                        .HasComment("일사(MJ/m2)");

                    b.Property<short?>("lcsCh")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("lcsCh")
                        .HasComment("최저운고(100m)");

                    b.Property<decimal?>("m005Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m005Te")
                        .HasComment("5cm 지중온도");

                    b.Property<decimal?>("m01Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m01Te")
                        .HasComment("10cm 지중온도");

                    b.Property<decimal?>("m02Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m02Te")
                        .HasComment("20cm 지중온도");

                    b.Property<decimal?>("m03Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m03Te")
                        .HasComment("30cm 지중온도");

                    b.Property<decimal?>("pa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("pa")
                        .HasComment("현지기압");

                    b.Property<sbyte>("paQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("paQcflag")
                        .HasComment("현지기압 정상여부 판별 정보");

                    b.Property<decimal?>("ps")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ps")
                        .HasComment("해면기압");

                    b.Property<sbyte>("psQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("psQcflag")
                        .HasComment("해면기압 정상여부 판별 정보");

                    b.Property<decimal?>("pv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("pv")
                        .HasComment("증기압");

                    b.Property<decimal?>("rn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("rn")
                        .HasComment("강수량");

                    b.Property<sbyte>("rnQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("rnQcflag")
                        .HasComment("강수량 정상여부 판별 정보");

                    b.Property<decimal?>("ss")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ss")
                        .HasComment("일조");

                    b.Property<sbyte>("ssQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("sQcflag")
                        .HasComment("일조 정상여부 판별 정보");

                    b.Property<string>("stnId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnId")
                        .HasComment("종관기상관측 지점 번호");

                    b.Property<string>("stnNm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnNm")
                        .HasComment("종관기상관측 지점명");

                    b.Property<decimal?>("ta")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ta")
                        .HasComment("기온");

                    b.Property<sbyte>("taQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("taQcflag")
                        .HasComment("기온 정상여부 판별 정보");

                    b.Property<decimal?>("td")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("td")
                        .HasComment("지면온도");

                    b.Property<DateTime>("tm")
                        .IsUnicode(false)
                        .HasColumnType("DATETIME")
                        .HasColumnName("tm")
                        .HasComment("샘플링 시간");

                    b.Property<decimal?>("ts")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ts")
                        .HasComment("지면온도");

                    b.Property<sbyte>("tsQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("tsQcflag")
                        .HasComment("지면온도 정상여부 판별 정보");

                    b.Property<short?>("vs")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("vs")
                        .HasComment("시정(10m)");

                    b.Property<short?>("wd")
                        .HasColumnType("SMALLINT(3)")
                        .HasColumnName("wd")
                        .HasComment("풍향");

                    b.Property<sbyte>("wdQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("wdQcflag")
                        .HasComment("풍향 정상여부 판별 정보");

                    b.Property<decimal?>("ws")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ws")
                        .HasComment("풍속");

                    b.Property<sbyte>("wsQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("wsQcflag")
                        .HasComment("풍속 정상여부 판별 정보");

                    b.HasKey("Id");

                    b.HasIndex("stnId", "tm")
                        .IsUnique();

                    b.ToTable("ASOSHourData");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.DamCodeDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DamCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DamCode");

                    b.Property<string>("DamName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DamName");

                    b.Property<decimal>("latitude")
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("Latitude")
                        .HasComment("위도");

                    b.Property<decimal>("longitude")
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("Longitude")
                        .HasComment("경도");

                    b.HasKey("Id");

                    b.HasIndex("DamCode")
                        .IsUnique();

                    b.ToTable("DamCodeList");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.DamDailyDatum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DamCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DamCode")
                        .HasComment("댐 코드");

                    b.Property<string>("dt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("dt")
                        .HasComment("MM-dd HH");

                    b.Property<decimal?>("inflowqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("inflowqy")
                        .HasComment("유입량");

                    b.Property<decimal?>("lowlevel")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("lowlevel")
                        .HasComment("댐 수위");

                    b.Property<DateTime>("obsryymtde")
                        .HasColumnType("DATETIME")
                        .HasColumnName("obsryymtde")
                        .HasComment("샘플링 시간");

                    b.Property<decimal?>("prcptqy")
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("prcptqy")
                        .HasComment("강우량");

                    b.Property<decimal?>("rsvwtqy")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("rsvwtqy")
                        .HasComment("저수량");

                    b.Property<decimal?>("rsvwtrt")
                        .HasColumnType("DECIMAL(5,1)")
                        .HasColumnName("rsvwtrt")
                        .HasComment("저수율");

                    b.Property<decimal?>("totdcwtrqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("totdcwtrqy")
                        .HasComment("총 방류량");

                    b.HasKey("Id");

                    b.HasIndex("DamCode", "obsryymtde")
                        .IsUnique();

                    b.ToTable("DamDailyData");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.DamHourDatum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DamCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DamCode")
                        .HasComment("댐 코드");

                    b.Property<decimal?>("inflowqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("inflowqy")
                        .HasComment("유입량");

                    b.Property<decimal?>("lowlevel")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("lowlevel")
                        .HasComment("댐 수위");

                    b.Property<DateTime>("obsrdt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("obsrdt")
                        .HasComment("샘플링 시간");

                    b.Property<decimal?>("rf")
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("rf")
                        .HasComment("강우량");

                    b.Property<decimal?>("rsvwtqy")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("rsvwtqy")
                        .HasComment("저수량");

                    b.Property<decimal?>("rsvwtrt")
                        .HasColumnType("DECIMAL(5,1)")
                        .HasColumnName("rsvwtrt")
                        .HasComment("저수율");

                    b.Property<decimal?>("totdcwtrqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("totdcwtrqy")
                        .HasComment("총 방류량");

                    b.HasKey("Id");

                    b.HasIndex("DamCode", "obsrdt")
                        .IsUnique();

                    b.ToTable("DamHourData");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.JoinDailyDatum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("DamCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DamCode")
                        .HasComment("댐 코드");

                    b.Property<decimal?>("avgCm10Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm10Te")
                        .HasComment("평균 10cm 지중온도(c)");

                    b.Property<decimal?>("avgCm20Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm20Te")
                        .HasComment("평균 20cm 지중온도(c)");

                    b.Property<decimal?>("avgCm30Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm30Te")
                        .HasComment("평균 30cm 지중온도(c)");

                    b.Property<decimal?>("avgCm5Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgCm5Te")
                        .HasComment("평균 5cm 지중온도(c)");

                    b.Property<decimal?>("avgLmac")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgLmac")
                        .HasComment("평균 중하층운량(10분위)");

                    b.Property<decimal?>("avgM05Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM05Te")
                        .HasComment("평균 0.5m 지중온도(c)");

                    b.Property<decimal?>("avgM10Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM10Te")
                        .HasComment("평균 1.0m 지중온도(c)");

                    b.Property<decimal?>("avgM15Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM15Te")
                        .HasComment("평균 1.5m 지중온도(c)");

                    b.Property<decimal?>("avgM30Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM30Te")
                        .HasComment("평균 3.0m 지중온도(c)");

                    b.Property<decimal?>("avgM50Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgM50Te")
                        .HasComment("평균 5.0m 지중온도(c)");

                    b.Property<decimal?>("avgPa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgPa")
                        .HasComment("평균 현지기압(hPa)");

                    b.Property<decimal?>("avgPs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgPs")
                        .HasComment("평균 해면기압(hPa)");

                    b.Property<decimal?>("avgPv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgPv")
                        .HasComment("평균 증기압(hPa)");

                    b.Property<decimal?>("avgRhm")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgRhm")
                        .HasComment("평균 상대습도(%)");

                    b.Property<decimal?>("avgTa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTa")
                        .HasComment("평균 기온(c)");

                    b.Property<decimal?>("avgTca")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTca")
                        .HasComment("평균 전운량(10분위)");

                    b.Property<decimal?>("avgTd")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTd")
                        .HasComment("평균 이슬점 온도(c)");

                    b.Property<decimal?>("avgTs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgTs")
                        .HasComment("평균 지면온도(c)");

                    b.Property<decimal?>("avgWs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("avgWs")
                        .HasComment("평균 풍속(m/s)");

                    b.Property<decimal?>("ddMefs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ddMefs")
                        .HasComment("일 최심신적설(cm)");

                    b.Property<string>("ddMefsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ddMefsHrmt")
                        .HasComment("일 최심신적설 시각");

                    b.Property<decimal?>("ddMes")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ddMes")
                        .HasComment("일 최심적설(cm)");

                    b.Property<string>("ddMesHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ddMesHrmt")
                        .HasComment("일 최심적설 시각");

                    b.Property<decimal?>("hr1MaxIcsr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hr1MaxIcsr")
                        .HasComment("1시간 최다 일사량(MJ/m2)");

                    b.Property<string>("hr1MaxIcsrHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("hr1MaxIcsrHrmt")
                        .HasComment("1시간 최다 일사시각(hhmi)");

                    b.Property<decimal?>("hr1MaxRn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hr1MaxRn")
                        .HasComment("1시간 최다강수량(mm)");

                    b.Property<string>("hr1MaxRnHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("hr1MaxRnHrmt")
                        .HasComment("1시간 최다강수량 시각");

                    b.Property<short?>("hr24SumRws")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("hr24SumRws")
                        .HasComment("풍정합(100m)");

                    b.Property<decimal?>("inflowqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("inflowqy")
                        .HasComment("유입량");

                    b.Property<string>("iscs")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("iscs")
                        .HasComment("일기현상");

                    b.Property<decimal?>("lowlevel")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("lowlevel")
                        .HasComment("댐 수위");

                    b.Property<decimal?>("maxInsWs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxInsWs")
                        .HasComment("최대 순간풍속(m/s)");

                    b.Property<string>("maxInsWsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxInsWsHrmt")
                        .HasComment("최대 순간풍속 시각");

                    b.Property<short?>("maxInsWsWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("maxInsWsWd")
                        .HasComment("최대 순간풍속 풍향(16방위)");

                    b.Property<decimal?>("maxPs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxPs")
                        .HasComment("최고 해면 기압(hPa)");

                    b.Property<string>("maxPsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxPsHrmt")
                        .HasComment("최고 해면기압 시각");

                    b.Property<decimal?>("maxTa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxTa")
                        .HasComment("최고 기온(c)");

                    b.Property<string>("maxTaHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxTaHrmt")
                        .HasComment("최고기온시각");

                    b.Property<short?>("maxWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("maxWd")
                        .HasComment("최다 풍향(16방위)");

                    b.Property<decimal?>("maxWs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("maxWs")
                        .HasComment("최대 풍속(m/s)");

                    b.Property<string>("maxWsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("maxWsHrmt")
                        .HasComment("최대 풍속 시각");

                    b.Property<short?>("maxWsWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("maxWsWd")
                        .HasComment("최대 풍속 풍향(16방위)");

                    b.Property<decimal?>("mi10MaxRn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("mi10MaxRn")
                        .HasComment("10분 최다강수량(mm)");

                    b.Property<string>("mi10MaxRnHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("mi10MaxRnHrmt")
                        .HasComment("10분 최다강수량 시각(mm)");

                    b.Property<decimal?>("minPs")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minPs")
                        .HasComment("최저 해면기압(hPa)");

                    b.Property<string>("minPsHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("minPsHrmt")
                        .HasComment("최저 해면기압 시각");

                    b.Property<decimal?>("minRhm")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minRhm")
                        .HasComment("최소 상대습도(%)");

                    b.Property<string>("minRhmHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("minRhmHrmt")
                        .HasComment("평균 상대습도 시각");

                    b.Property<decimal?>("minTa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minTa")
                        .HasComment("최저 기온(c)");

                    b.Property<string>("minTaHrmt")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("minTaHrmt")
                        .HasComment("최저기온시각");

                    b.Property<decimal?>("minTg")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("minTg")
                        .HasComment("최저 초상온도(c)");

                    b.Property<decimal?>("n99Rn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("n99Rn")
                        .HasComment("9-9 강수(mm)");

                    b.Property<DateTime>("obsryymtde")
                        .HasColumnType("DATETIME")
                        .HasColumnName("obsryymtde")
                        .HasComment("샘플링 시간");

                    b.Property<decimal?>("prcptqy")
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("prcptqy")
                        .HasComment("강우량");

                    b.Property<decimal?>("rsvwtqy")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("rsvwtqy")
                        .HasComment("저수량");

                    b.Property<decimal?>("rsvwtrt")
                        .HasColumnType("DECIMAL(5,1)")
                        .HasColumnName("rsvwtrt")
                        .HasComment("저수율");

                    b.Property<decimal?>("ssDur")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ssDur")
                        .HasComment("가조시간(hr)");

                    b.Property<string>("stnId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnId")
                        .HasComment("종관기상관측 지점번호");

                    b.Property<string>("stnNm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnNm")
                        .HasComment("종관기상관측 지점명");

                    b.Property<decimal?>("sumDpthFhsc")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumDpthFhsc")
                        .HasComment("합계 3시간 신적설(cm)");

                    b.Property<decimal?>("sumFogDur")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumFogDur")
                        .HasComment("안개 계속 시간(hr)");

                    b.Property<decimal?>("sumGsr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumGsr")
                        .HasComment("합계 일사량(MJ/m2)");

                    b.Property<decimal?>("sumLrgEv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumLrgEv")
                        .HasComment("합계 대형증발량(mm)");

                    b.Property<decimal?>("sumRn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumRn")
                        .HasComment("일강수량(mm)");

                    b.Property<decimal?>("sumRnDur")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumRnDur")
                        .HasComment("강수 계속시간(hr)");

                    b.Property<decimal?>("sumSmlEv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumSmlEv")
                        .HasComment("합계 소형증발량(mm)");

                    b.Property<decimal?>("sumSsHr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("sumSsHr")
                        .HasComment("합계 일조 시간(hr)");

                    b.Property<decimal?>("totdcwtrqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("totdcwtrqy")
                        .HasComment("총 방류량");

                    b.HasKey("Id");

                    b.HasIndex("DamCode", "stnId", "obsryymtde")
                        .IsUnique();

                    b.ToTable("JoinDailyData");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.JoinHourDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("DamCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DamCode")
                        .HasComment("댐 코드");

                    b.Property<short?>("clfmAbbrCd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("clfmAbbrCd")
                        .HasComment("운형");

                    b.Property<decimal?>("dc10LmcsCa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("dc10LmcsCa")
                        .HasComment("중하층운량");

                    b.Property<decimal?>("dc10Tca")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("dc10Tca")
                        .HasComment("전운량");

                    b.Property<short?>("dmstMtphNo")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("dmstMtphNo")
                        .HasComment("현상번호");

                    b.Property<decimal?>("dsnw")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("dsnw")
                        .HasComment("적설(cm)");

                    b.Property<short?>("gndSttCd")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("gndSttCd")
                        .HasComment("지면상태");

                    b.Property<decimal?>("hm")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hm")
                        .HasComment("습도");

                    b.Property<sbyte>("hmQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("hmQcflag")
                        .HasComment("습도 정상여부 판별 정보");

                    b.Property<decimal?>("hr3Fhsc")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("hr3Fhsc")
                        .HasComment("3시간 신적설(cm)");

                    b.Property<decimal?>("icsr")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("icsr")
                        .HasComment("일사(MJ/m2)");

                    b.Property<decimal?>("inflowqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("inflowqy")
                        .HasComment("유입량");

                    b.Property<short?>("lcsCh")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("lcsCh")
                        .HasComment("최저운고(100m)");

                    b.Property<decimal?>("lowlevel")
                        .HasColumnType("DECIMAL(10,4)")
                        .HasColumnName("lowlevel")
                        .HasComment("댐 수위");

                    b.Property<decimal?>("m005Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m005Te")
                        .HasComment("5cm 지중온도");

                    b.Property<decimal?>("m01Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m01Te")
                        .HasComment("10cm 지중온도");

                    b.Property<decimal?>("m02Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m02Te")
                        .HasComment("20cm 지중온도");

                    b.Property<decimal?>("m03Te")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("m03Te")
                        .HasComment("30cm 지중온도");

                    b.Property<DateTime>("obsrdt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("obsrdt")
                        .HasComment("샘플링 시간");

                    b.Property<decimal?>("pa")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("pa")
                        .HasComment("현지기압");

                    b.Property<sbyte>("paQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("paQcflag")
                        .HasComment("현지기압 정상여부 판별 정보");

                    b.Property<decimal?>("ps")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ps")
                        .HasComment("해면기압");

                    b.Property<sbyte>("psQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("psQcflag")
                        .HasComment("해면기압 정상여부 판별 정보");

                    b.Property<decimal?>("pv")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("pv")
                        .HasComment("증기압");

                    b.Property<decimal?>("rf")
                        .HasColumnType("DECIMAL(8,2)")
                        .HasColumnName("rf")
                        .HasComment("강우량");

                    b.Property<decimal?>("rn")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("rn")
                        .HasComment("강수량");

                    b.Property<sbyte>("rnQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("rnQcflag")
                        .HasComment("강수량 정상여부 판별 정보");

                    b.Property<decimal?>("rsvwtqy")
                        .HasColumnType("DECIMAL(18,4)")
                        .HasColumnName("rsvwtqy")
                        .HasComment("저수량");

                    b.Property<decimal?>("rsvwtrt")
                        .HasColumnType("DECIMAL(5,1)")
                        .HasColumnName("rsvwtrt")
                        .HasComment("저수율");

                    b.Property<decimal?>("ss")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ss")
                        .HasComment("일조");

                    b.Property<sbyte>("ssQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("sQcflag")
                        .HasComment("일조 정상여부 판별 정보");

                    b.Property<string>("stnId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnId")
                        .HasComment("종관기상관측 지점 번호");

                    b.Property<string>("stnNm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("stnNm")
                        .HasComment("종관기상관측 지점명");

                    b.Property<decimal?>("ta")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ta")
                        .HasComment("기온");

                    b.Property<sbyte>("taQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("taQcflag")
                        .HasComment("기온 정상여부 판별 정보");

                    b.Property<decimal?>("td")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("td")
                        .HasComment("지면온도");

                    b.Property<decimal?>("totdcwtrqy")
                        .HasColumnType("DECIMAL(15,3)")
                        .HasColumnName("totdcwtrqy")
                        .HasComment("총 방류량");

                    b.Property<decimal?>("ts")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ts")
                        .HasComment("지면온도");

                    b.Property<sbyte>("tsQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("tsQcflag")
                        .HasComment("지면온도 정상여부 판별 정보");

                    b.Property<short?>("vs")
                        .HasColumnType("SMALLINT(4)")
                        .HasColumnName("vs")
                        .HasComment("시정(10m)");

                    b.Property<short?>("wd")
                        .HasColumnType("SMALLINT(3)")
                        .HasColumnName("wd")
                        .HasComment("풍향");

                    b.Property<sbyte>("wdQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("wdQcflag")
                        .HasComment("풍향 정상여부 판별 정보");

                    b.Property<decimal?>("ws")
                        .HasColumnType("DECIMAL(6,2)")
                        .HasColumnName("ws")
                        .HasComment("풍속");

                    b.Property<sbyte>("wsQcflag")
                        .HasColumnType("TINYINT")
                        .HasColumnName("wsQcflag")
                        .HasComment("풍속 정상여부 판별 정보");

                    b.HasKey("Id");

                    b.HasIndex("DamCode", "stnId", "obsrdt")
                        .IsUnique();

                    b.ToTable("JoinHourData");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.JoinRsvDailyDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("측정날짜");

                    b.Property<string>("Country")
                        .HasColumnType("longtext")
                        .HasComment("저수지위치");

                    b.Property<string>("FacCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("저수지코드");

                    b.Property<string>("FacName")
                        .HasColumnType("longtext")
                        .HasComment("저수지이름");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("저수율");

                    b.Property<decimal?>("WaterLevel")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("저수지수위");

                    b.Property<decimal?>("avgCm10Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 10cm 지중온도(c)");

                    b.Property<decimal?>("avgCm20Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 20cm 지중온도(c)");

                    b.Property<decimal?>("avgCm30Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 30cm 지중온도(c)");

                    b.Property<decimal?>("avgCm5Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 5cm 지중온도(c)");

                    b.Property<decimal?>("avgLmac")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 중하층운량(10분위)");

                    b.Property<decimal?>("avgM05Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 0.5m 지중온도(c)");

                    b.Property<decimal?>("avgM10Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 1.0m 지중온도(c)");

                    b.Property<decimal?>("avgM15Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 1.5m 지중온도(c)");

                    b.Property<decimal?>("avgM30Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 3.0m 지중온도(c)");

                    b.Property<decimal?>("avgM50Te")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 5.0m 지중온도(c)");

                    b.Property<decimal?>("avgPa")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 현지기압(hPa)");

                    b.Property<decimal?>("avgPs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 해면기압(hPa)");

                    b.Property<decimal?>("avgPv")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 중기압(hPa)");

                    b.Property<decimal?>("avgRhm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 상대습도(%)");

                    b.Property<decimal?>("avgTa")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균기온(c)");

                    b.Property<decimal?>("avgTca")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 전운량(10분위)");

                    b.Property<decimal?>("avgTd")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 이슬점 온도(c)");

                    b.Property<decimal?>("avgTs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 지면온도(c)");

                    b.Property<decimal?>("avgWs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("평균 풍속(m/s)");

                    b.Property<decimal?>("ddMefs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("일 최심신적설(cm)");

                    b.Property<string>("ddMefsHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("일 최심신적설 시각");

                    b.Property<decimal?>("ddMes")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("일 최심적설(cm)");

                    b.Property<string>("ddMesHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("일 최심적설 시각");

                    b.Property<string>("dt")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("변환시간");

                    b.Property<decimal?>("hr1MaxIcsr")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("1시간 최대 일사량(MJ/m2)");

                    b.Property<string>("hr1MaxIcsrHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("1시간 최다 일사시각(MJ/m2)");

                    b.Property<decimal?>("hr1MaxRn")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("1시간 최다강수량(mm)");

                    b.Property<string>("hr1MaxRnHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("1시간 최다강수량 시각");

                    b.Property<short?>("hr24SumRws")
                        .HasColumnType("SMALLINT(4)")
                        .HasComment("풍정합(100m)");

                    b.Property<string>("iscs")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasComment("일기현상");

                    b.Property<decimal?>("maxInsWs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최대 순간풍속(m/s)");

                    b.Property<string>("maxInsWsHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("최대 순간풍속 시각");

                    b.Property<short?>("maxInsWsWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasComment("최대 순간풍속 풍향(16방위)");

                    b.Property<decimal?>("maxPs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최고 해면기압");

                    b.Property<string>("maxPsHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("최고 해면기압 시각");

                    b.Property<decimal?>("maxTa")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최고기온(c)");

                    b.Property<string>("maxTaHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("최고기온시간");

                    b.Property<short?>("maxWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasComment("최다 풍향(16방위)");

                    b.Property<decimal?>("maxWs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최대 풍속(m/s)");

                    b.Property<string>("maxWsHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("최대 풍속 시각");

                    b.Property<short?>("maxWsWd")
                        .HasColumnType("SMALLINT(4)")
                        .HasComment("최대 충속 풍향(16방위)");

                    b.Property<decimal?>("mi10MaxRn")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("10분 최다강수량(mm)");

                    b.Property<string>("mi10MaxRnHrmt")
                        .HasPrecision(6, 2)
                        .HasColumnType("longtext")
                        .HasComment("10분 최다강수량 시각(mm)");

                    b.Property<decimal?>("minPs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최저 해면기압");

                    b.Property<string>("minPsHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("최저 해면기압 시각");

                    b.Property<decimal?>("minRhm")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최대 상대습도(%)");

                    b.Property<string>("minRhmHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("평균 상대습도 시각");

                    b.Property<decimal?>("minTa")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최저기온(c)");

                    b.Property<string>("minTaHrmt")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasComment("최저기온시간");

                    b.Property<decimal?>("minTg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("최저 초상온도(c)");

                    b.Property<decimal?>("n99Rn")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("9-9 강수(mm)");

                    b.Property<decimal?>("ssDur")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("가조시간(hr)");

                    b.Property<string>("stnId")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("종관기상관측 지점번호");

                    b.Property<string>("stnNm")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("종관기상관측 지점명");

                    b.Property<decimal?>("sumDpthFhsc")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("합계 3시간 신적설(cm)");

                    b.Property<decimal?>("sumFogDur")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("안개 계속 시간(hr)");

                    b.Property<decimal?>("sumGsr")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("합계 일사량(MJ/m2)");

                    b.Property<decimal?>("sumLrgEv")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("합계 대형증발량(mm)");

                    b.Property<decimal?>("sumRn")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("일강수량(mm)");

                    b.Property<decimal?>("sumRnDur")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("강수계속시간");

                    b.Property<decimal?>("sumSmlEv")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("합계 소형증발량(mm)");

                    b.Property<decimal?>("sumSsHr")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasComment("합계 일조 시간(hr)");

                    b.HasKey("Id");

                    b.HasIndex("FacCode", "CheckDate")
                        .IsUnique();

                    b.ToTable("JoinRsvDailyData");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.Meta_CheckPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Category");

                    b.Property<DateTime>("DataBeginTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("DataBeginTime");

                    b.Property<DateTime>("DataLastTime")
                        .HasColumnType("DateTime")
                        .HasColumnName("DataLastTime");

                    b.Property<DateTime>("DateCheckPoint")
                        .HasColumnType("DateTime")
                        .HasColumnName("DateCheckPoint");

                    b.Property<sbyte>("IsComplete")
                        .HasColumnType("TINYINT")
                        .HasColumnName("IsComplete");

                    b.Property<sbyte>("LastPage")
                        .HasColumnType("TINYINT")
                        .HasColumnName("LastPage");

                    b.Property<sbyte>("RetryCount")
                        .HasColumnType("TINYINT")
                        .HasColumnName("RetryCount");

                    b.Property<string>("TargetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TargetCode");

                    b.HasKey("Id");

                    b.HasIndex("TargetCode");

                    b.ToTable("Meta_CheckPoint");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.Meta_ServerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("LogDate");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("LogLevel");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("Message");

                    b.HasKey("Id");

                    b.ToTable("ServerLogList");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.Meta_TryCount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("ID");

                    b.Property<int>("Count")
                        .HasColumnType("INT")
                        .HasColumnName("Count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("TryDate")
                        .HasColumnType("DateTime")
                        .HasColumnName("TryDate");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Meta_TryCount");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.RsvCodeDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("BeneficiaryArea")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("수혜면적");

                    b.Property<string>("BodyFormat")
                        .HasColumnType("longtext")
                        .HasComment("제체형식");

                    b.Property<decimal?>("BodyHeight")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("제체높이");

                    b.Property<decimal?>("BodyLength")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("제체길이");

                    b.Property<decimal?>("BodyVolume")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("제체제적");

                    b.Property<int?>("Classification")
                        .HasColumnType("int")
                        .HasComment("종별");

                    b.Property<string>("Division")
                        .HasColumnType("longtext")
                        .HasComment("구분");

                    b.Property<decimal?>("EffectiveStorage")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("유효저수량");

                    b.Property<string>("FacCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("표준 코드");

                    b.Property<string>("FacName")
                        .HasColumnType("longtext")
                        .HasComment("시설명");

                    b.Property<decimal?>("FloodArea")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("홍수면적");

                    b.Property<int?>("FloodFrequency")
                        .HasColumnType("int")
                        .HasComment("홍수빈도");

                    b.Property<decimal?>("FloodLevel")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("홍수위");

                    b.Property<decimal?>("FullArea")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("만수면적");

                    b.Property<decimal?>("Gunnery")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("사수량");

                    b.Property<decimal?>("Janitor")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("사수위");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasComment("소재지");

                    b.Property<int?>("OneStepFrequency")
                        .HasColumnType("int")
                        .HasComment("한발빈도");

                    b.Property<decimal?>("TotalStorage")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("총저수량");

                    b.Property<string>("WaterIntake")
                        .HasColumnType("longtext")
                        .HasComment("취수형식");

                    b.Property<decimal?>("WaterLevel")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("만수위");

                    b.Property<decimal?>("WatershedArea")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("유역면적");

                    b.Property<DateTime>("YearOfConstruction")
                        .HasColumnType("datetime(6)")
                        .HasComment("준공년도");

                    b.Property<DateTime>("YearOfStart")
                        .HasColumnType("datetime(6)")
                        .HasComment("착공년도");

                    b.HasKey("Id");

                    b.HasIndex("FacCode")
                        .IsUnique();

                    b.ToTable("RsvCodeList");
                });

            modelBuilder.Entity("PublicDBLib.MariaDB.RsvDailyDatum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("측정날짜");

                    b.Property<string>("Country")
                        .HasColumnType("longtext")
                        .HasComment("저수지위치");

                    b.Property<string>("FacCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasComment("저수지코드");

                    b.Property<string>("FacName")
                        .HasColumnType("longtext")
                        .HasComment("저수지이름");

                    b.Property<decimal?>("Rate")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("저수율");

                    b.Property<decimal?>("WaterLevel")
                        .HasPrecision(20, 2)
                        .HasColumnType("decimal(20,2)")
                        .HasComment("저수지수위");

                    b.HasKey("Id");

                    b.HasIndex("FacCode", "CheckDate")
                        .IsUnique();

                    b.ToTable("RsvDailyData");
                });
#pragma warning restore 612, 618
        }
    }
}
